const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
const source=fs.readFileSync('assets/index-header-avatar-20261001.js','utf8');const code=source.slice(source.indexOf('// Refresh private header avatars'));
function surface(){const listeners=new Map(),intervals=new Map(),timeouts=new Map();let sequence=0;return {listeners,intervals,timeouts,visibilityState:'visible',addEventListener(name,fn){listeners.set(name,fn)},removeEventListener(name){listeners.delete(name)},setInterval(fn,ms){assert.equal(ms,3000000);intervals.set(++sequence,fn);return sequence},clearInterval(id){intervals.delete(id)},setTimeout(fn){timeouts.set(++sequence,fn);return sequence},clearTimeout(id){timeouts.delete(id)},emit(name){listeners.get(name)?.()}};}
(async()=>{
 const ctx={};vm.createContext(ctx);vm.runInContext(code,ctx);const windowTarget=surface(),documentTarget=surface();let calls=0,mode='ok',urls=[],resolvePending;
 const client={storage:{from(bucket){assert.equal(bucket,'avatars');return {async createSignedUrl(path,expiry){calls++;assert.equal(path,'profile/photo.jpg');assert.equal(expiry,3600);if(mode==='pending')return new Promise(resolve=>resolvePending=resolve);if(mode==='fail')return {error:Error('network')};return {data:{signedUrl:`signed-photo-${calls}`}}}}}}};
 const stop=ctx.watchHeaderAvatar({path:'profile/photo.jpg',userId:'user',client,setUrl:url=>urls.push(url),windowTarget,documentTarget});const flush=()=>new Promise(resolve=>setImmediate(resolve));await flush();assert.equal(urls.at(-1),'signed-photo-1');
 [...windowTarget.intervals.values()][0]();await flush();assert.equal(urls.at(-1),'signed-photo-2','renews before expiry');windowTarget.emit('focus');await flush();assert.equal(calls,3);documentTarget.visibilityState='hidden';documentTarget.emit('visibilitychange');await flush();assert.equal(calls,3);documentTarget.visibilityState='visible';documentTarget.emit('visibilitychange');await flush();assert.equal(calls,4);
 for(let j=0;j<4;j++){windowTarget.emit('volleycoach:header-avatar-error');await flush();}assert.equal(calls,6,'image failures have bounded retries');windowTarget.emit('volleycoach:header-avatar-loaded');windowTarget.emit('volleycoach:header-avatar-error');await flush();assert.equal(calls,7);
 mode='fail';windowTarget.emit('focus');await flush();assert.equal(urls.at(-1),'signed-photo-7','network failure retains previous image');assert.equal(windowTarget.timeouts.size,1);mode='pending';[...windowTarget.intervals.values()][0]();await flush();stop();resolvePending({data:{signedUrl:'old-account-photo'}});await flush();assert.notEqual(urls.at(-1),'old-account-photo','old account cannot replace current avatar');assert.equal(windowTarget.listeners.size,0);assert.equal(windowTarget.intervals.size,0);assert.equal(windowTarget.timeouts.size,0);assert.equal(documentTarget.listeners.size,0);
 const fallback=[];ctx.watchHeaderAvatar({path:'',userId:'user',client,setUrl:value=>fallback.push(value),windowTarget,documentTarget});assert.equal(fallback[0],'');console.log('PASS: initial avatar, renewal, focus/resume, error recovery, fallback and logout cleanup');
})().catch(error=>{console.error(error);process.exitCode=1});
