const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
const source=fs.readFileSync('assets/index-match-venue-20261001.js','utf8');const calendar=source.slice(source.indexOf('function lN('),source.indexOf('const Sh=',source.indexOf('function lN(')));const helpers=source.slice(source.indexOf('// Local/away selection'));
function nodes(tree,predicate){if(!tree||typeof tree!=='object')return [];return [...(predicate(tree)?[tree]:[]),...[tree.props?.children].flat(Infinity).flatMap(child=>nodes(child,predicate))];}
(async()=>{
 const now=new Date();const team={id:'team',name:'CV Bunyola'};const league=[{context_team_id:'team',is_own:true,name:'CV Bunyola',logo:'bunyola.svg'},{context_team_id:'team',is_own:false,name:'Rival',team_key:'rival',logo:'rival.svg'}];
 const event={id:'event',team_id:'team',event_type:'match',title:'Partido',starts_at:now.toISOString(),ends_at:new Date(+now+120*60000).toISOString(),payload:{opponent:'Rival',opponent_key:'rival',match_venue:'away',stats:{keep:true},result:'3-1'}};
 const key=`team:${now.getFullYear()}-${now.getMonth()}`;let cursor=0,slots=[],saved;
 const hooks={useMemo(fn){return fn()},useEffect(){},useState(initial){const j=cursor++;if(!(j in slots))slots[j]=typeof initial==='function'?initial():initial;return[slots[j],value=>slots[j]=typeof value==='function'?value(slots[j]):value]}};
 const jsx=(type,props)=>({type,props});const noop=()=>null;
 const ctx={console};
 Object.assign(ctx,{_:hooks,i:{jsx,jsxs:jsx,Fragment:'fragment'},an:()=>({identity:{teams:[team],profile:{role:'coach',id:'staff',club_id:'club'},season:{id:'season'}}}),ri:new Map([[key,{events:[event],birthdays:[],leagueTeams:league}]]),Bc:row=>row?.logo,Qc:url=>url,as:x=>String(x||'').toLowerCase().replace(/\s/g,''),$0:{cvbunyola:'bunyola.svg'},$c:{training:{label:'Entrenamiento',icon:noop},match:{label:'Partido',icon:noop},friendly:{label:'Amistoso',icon:noop},tournament:{label:'Torneo',icon:noop}},rN:[['training','Entrenamiento'],['match','Partido'],['friendly','Amistoso'],['tournament','Torneo']],aN:['L','M','X','J','V','S','D'],sN:Array(12).fill('Mes'),Q:{from(){return {insert(row){saved=row;return this},update(row){saved=row;return this},eq(){return this},select(){return this},single(){return Promise.resolve({data:{id:event.id,...saved},error:null})}}}},window:{confirm:()=>true}});
 for(const name of ['fv','bi','En','Kc','pn','ij','aj','iN','yr','Gx','Fx','HE'])ctx[name]=noop;
 vm.createContext(ctx);vm.runInContext(calendar+helpers,ctx);const render=()=>{cursor=0;return ctx.pN()};let tree=render();const component=name=>nodes(tree,x=>x.type===ctx[name])[0];const label=(form,name)=>nodes(form,x=>x.type==='label'&&nodes(x,y=>y.props?.children===name).length)[0];
 const matchup={ownName:'CV Bunyola',ownLogo:'bunyola.svg',opponentName:'Rival',opponentLogo:'rival.svg'};
 for(const venue of ['home','away']){
  const data={...event,payload:{...event.payload,match_venue:venue}};const card=ctx.dN({event:data,leagueTeams:league,onOpen:noop});const visual=nodes(card,x=>x.type===ctx.MatchVenueVisual)[0];const ordered=ctx.MatchVenueVisual(visual.props);const logos=nodes(ordered,x=>x.type===ctx.fv).map(x=>x.props.src);assert.equal(logos.join(','),venue==='away'?'rival.svg,bunyola.svg':'bunyola.svg,rival.svg');const home=ctx.MatchVenueHome({event:data,ownLogo:'bunyola.svg',opponentName:'Rival',opponentLogo:'rival.svg'});assert.equal(nodes(home,x=>x.type===ctx.HE).map(x=>x.props.src).join(','),logos.join(','));
 }
 assert.equal(ctx.matchVenue({payload:{}}),'home','existing matches keep current order');
 nodes(tree,x=>x.props?.className==='calendar-add-button')[0].props.onClick();tree=render();let modal=component('fN');let form=ctx.fN(modal.props);assert(!label(form,'Jugamos como'),'training has no local/away selector');let type=nodes(label(form,'Tipo'),x=>x.type==='select')[0];type.props.onChange({target:{value:'match'}});tree=render();modal=component('fN');form=ctx.fN(modal.props);let venue=nodes(label(form,'Jugamos como'),x=>x.type==='select')[0];assert.equal(venue.props.value,'home');venue.props.onChange({target:{value:'away'}});nodes(label(form,'Otro rival'),x=>x.type==='input')[0].props.onChange({target:{value:'Rival'}});tree=render();modal=component('fN');form=ctx.fN(modal.props);const preview=nodes(form,x=>x.type===ctx.MatchVenuePreview)[0];assert.equal(nodes(ctx.MatchVenuePreview(preview.props),x=>x.type===ctx.fv).map(x=>x.props.src).join(','),'rival.svg,bunyola.svg');await modal.props.onSubmit({preventDefault(){}});assert.equal(saved.payload.match_venue,'away','new match saves away');
 tree=render();const agenda=nodes(tree,x=>x.type===ctx.dN)[0];agenda.props.onOpen(event);tree=render();component('hN').props.onEdit(event);tree=render();modal=component('fN');assert.equal(modal.props.form.match_venue,'away','edit restores venue');form=ctx.fN(modal.props);nodes(label(form,'Jugamos como'),x=>x.type==='select')[0].props.onChange({target:{value:'home'}});tree=render();await component('fN').props.onSubmit({preventDefault(){}});assert.equal(saved.payload.match_venue,'home');assert.equal(saved.payload.result,'3-1');assert.equal(saved.payload.stats.keep,true,'editing preserves statistics');
 console.log('PASS: local/away create, edit, persistence, preview, calendar/home logo order, legacy default and statistics preservation');
})().catch(error=>{console.error(error);process.exitCode=1});
